#!/bin/bash
## A file for storing handy aliases.

# ---
## Help
# Print this message.
# Usage: `$ alias-help`
alias alias-help="comment_docs ~/scripts/shell/aliases"

# ---
## Commands

### --- please ---
# Run command with sudo.
# Usage: `$ please <command>`
alias please='sudo'

### --- pretty-please ---
# Run the last command with sudo.
# Usage: `$ pretty-please`
alias pretty-please='please $(history -p \!\!)'

### --- clipboard ---
# Pipe output to clipboard.
# Usage: `$ echo "Hello, World!" | clipboard`
alias clipboard='xclip -sel clip'

### --- venv-activate ---
# Activate the python venv in the current directory.
# Usage: `$ venv-activate`
alias venv-activate='source venv/bin/activate'

# ---
## Apps

### --- files ---
# Run a commandline file manager.
# Usage: `$ files`
# See `man files` for complete documentation.
alias files='ranger'

### --- mdr ---
# Run a terminal based markdown renderer with custom theme.
# Usage: `$ mdr [file]`
# See `mdv -h` for complete documentation.
alias mdr='md_render'

# ---
## Permissions

### --- execution permission ---
# Grant/take execution permission to/from a file.
# Usage: `$ exec-enable file`
# Usage: `$ exec-disable file`
alias exec-enable='chmod +x'
alias exec-disable='chmod -x'
