#!/bin/sh
## comment_docs 
# Render all (#) comments of a file as markdown
# Usege: `comment_docs file`

comment_docs() {
    docs=$(awk '/^#/{print substr($0, 2, length($0))}' "$1")
    echo "$docs" | md_render
}
