#! /bin/sh

export MDV_THEME=757.2295

CUSTOM_SHELL_SCRIPT_DIR=~/scripts/shell

## Source files

# shellcheck source=./shell/md_render
. $CUSTOM_SHELL_SCRIPT_DIR/md_render
# shellcheck source=./shell/comment_docs
. $CUSTOM_SHELL_SCRIPT_DIR/comment_docs
# shellcheck source=./shell/aliases
. $CUSTOM_SHELL_SCRIPT_DIR/aliases
